apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role
subjects:
  - kind: ServiceAccount
    name: backend-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dashboard-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dashboard-role
subjects:
  - kind: ServiceAccount
    name: web-dashboard-service-account
