version: "3.8"

services:
  backend:
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile.prod
    ports:
      - "8000:8000"
    restart: always

  web-dashboard:
    build:
      context: ../apps/web-dashboard
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    restart: always
